export type RuleErrorCode =
  | 'WRONG_PHASE'
  | 'WRONG_ACTOR'
  | 'NOT_ACTIVE_ACTOR'
  | 'GAME_ALREADY_STARTED'
  | 'WORKSTATION_OCCUPIED'
  | 'SAME_DEPARTMENT_AS_PREVIOUS_DAY'
  | 'WORKSTATION_RESERVED'
  | 'SANDRA_DEPARTMENT_BLOCKED'
  | 'INVARIANT_FAILED';
